In [24]:
from data import X_train, X_test, y_train, y_test
import numpy as np

np.shape(X_train)

(455, 30)

In [85]:
n_features = X_train.shape[1]
print(n_features)
feature_indices = np.random.choice(n_features, 10, replace=False)
print(feature_indices)
X = X_train[:, feature_indices]
X

30
[ 9 12 19 16 21 10  7  6  3  1]


array([[5.912e-02, 1.479e+00, 1.802e-03, ..., 1.063e-02, 5.827e+02,
        1.327e+01],
       [5.922e-02, 3.195e+00, 2.085e-03, ..., 7.395e-02, 6.845e+02,
        2.013e+01],
       [7.102e-02, 2.204e+00, 6.005e-03, ..., 7.741e-02, 4.678e+02,
        1.768e+01],
       ...,
       [5.572e-02, 2.587e+00, 1.892e-03, ..., 1.519e-01, 1.288e+03,
        2.706e+01],
       [5.934e-02, 2.684e+00, 1.461e-03, ..., 2.638e-02, 4.074e+02,
        1.845e+01],
       [6.688e-02, 2.076e+00, 3.599e-03, ..., 3.688e-02, 5.848e+02,
        2.070e+01]], shape=(455, 10))

In [53]:
feature_indices

array([26, 27,  9, 28,  3, 24, 13, 17, 21,  1,  2, 29, 16,  7, 18, 15,  8,
       22,  5, 19,  6, 12, 14, 10, 20,  4, 11, 25,  0, 23], dtype=int32)

In [ ]:
#Lista de numeros del 1 al 30 enteros
idx = np.linspace(0,29,30).astype(int)
X = X_train[:, idx]
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [82]:
X = X_train[:, idx]
X

array([[1.377e+01, 1.327e+01, 8.806e+01, ..., 5.802e-02, 2.823e-01,
        6.794e-02],
       [1.468e+01, 2.013e+01, 9.474e+01, ..., 1.609e-01, 3.029e-01,
        8.216e-02],
       [1.240e+01, 1.768e+01, 8.147e+01, ..., 7.370e-02, 2.556e-01,
        9.359e-02],
       ...,
       [2.031e+01, 2.706e+01, 1.329e+02, ..., 1.697e-01, 3.151e-01,
        7.999e-02],
       [1.150e+01, 1.845e+01, 7.328e+01, ..., 6.544e-02, 2.740e-01,
        6.487e-02],
       [1.387e+01, 2.070e+01, 8.977e+01, ..., 6.845e-02, 2.249e-01,
        8.492e-02]], shape=(455, 30))

In [51]:
X_train

array([[1.377e+01, 1.327e+01, 8.806e+01, ..., 5.802e-02, 2.823e-01,
        6.794e-02],
       [1.468e+01, 2.013e+01, 9.474e+01, ..., 1.609e-01, 3.029e-01,
        8.216e-02],
       [1.240e+01, 1.768e+01, 8.147e+01, ..., 7.370e-02, 2.556e-01,
        9.359e-02],
       ...,
       [2.031e+01, 2.706e+01, 1.329e+02, ..., 1.697e-01, 3.151e-01,
        7.999e-02],
       [1.150e+01, 1.845e+01, 7.328e+01, ..., 6.544e-02, 2.740e-01,
        6.487e-02],
       [1.387e+01, 2.070e+01, 8.977e+01, ..., 6.845e-02, 2.249e-01,
        8.492e-02]], shape=(455, 30))

In [77]:

X[:,0]

array([0.03732 , 0.2914  , 0.2403  , 0.1373  , 0.7026  , 0.07153 ,
       0.1472  , 0.2873  , 0.1882  , 0.2102  , 0.3639  , 0.08112 ,
       0.06648 , 0.03469 , 0.4107  , 0.01854 , 0.105   , 0.      ,
       0.      , 0.08615 , 0.01335 , 0.7242  , 0.4609  , 0.7119  ,
       0.3241  , 0.5539  , 0.4646  , 0.3617  , 0.1453  , 0.1145  ,
       0.01824 , 0.7892  , 0.3786  , 0.1144  , 0.1811  , 0.3779  ,
       0.      , 0.3664  , 0.145   , 0.1326  , 0.3442  , 0.02533 ,
       0.04116 , 0.3009  , 0.4756  , 0.6943  , 0.08636 , 0.3064  ,
       0.7356  , 0.2573  , 0.678   , 0.1449  , 0.305   , 0.1456  ,
       0.2962  , 0.102   , 0.2803  , 0.4425  , 0.2535  , 0.1434  ,
       0.2177  , 0.6783  , 0.1889  , 0.2247  , 0.03582 , 0.2298  ,
       0.4967  , 0.2992  , 0.03046 , 0.07915 , 0.3438  , 0.4589  ,
       0.3201  , 0.1811  , 0.5274  , 0.5553  , 0.3879  , 0.2299  ,
       0.162   , 0.1533  , 0.0498  , 0.1624  , 0.4146  , 0.2923  ,
       0.2802  , 0.1101  , 0.5372  , 0.6922  , 0.2123  , 0.315